services:
  - type: web
    name: pv-power-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt && python Web_App/save_model.py
    startCommand: gunicorn --chdir Web_App app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
